--- @type LazySpec[]
return {
    {
        "romus204/tree-sitter-manager.nvim",
        opts = {
            ensure_installed = {
                "bash",
                "c",
                "cmake",
                "comment",
                "cpp",
                "dockerfile",
                "dot",
                "doxygen",
                "gitcommit",
                "json",
                "json5",
                "lua",
                "make",
                "markdown",
                "markdown_inline",
                "ninja",
                "proto",
                "python",
                "query",
                "regex",
                "thrift",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
                "zsh",
            },
        },
    },
}
